// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"gozero_learn/model_learn/user_gorm/api/internal/svc"
	"net/http"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: loginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/apiv1/users"),
	)
}
