// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type LoginRequest struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type UserInfoResponse struct {
	Id       uint   `json:"id"`
	UserName string `json:"userName"`
	Addr     string `json:"addr"`
}
